### PR TITLE
Wrap SLIP packet reads into a Python generator

### PR DESCRIPTION
**Pull request by projectgus**
#103 introduced a regression when reading flash, which was previously fixed in #93.

With this PR, read_flash uses 7% of the read/select syscalls compared to current master. On my i7 there isn't a noticeable performance difference, but it will hopefully improve performance on slow systems like Raspberry Pi (as per #93)

A side effect of the change is an unintentional fix to sync() behaviour, which didn't retry cleanly before. This is less of a relevant problem now that we sync at max 115200bps, though.

# all the stats!

## Before

```
$ time esptool.py -b 1500000 -p /dev/ttyUSB0 read_flash 0x20000 393307 0x20000-readback.bin
esptool.py v1.0.2-dev
Connecting...
Running Cesanta flasher stub...
Reading 393307 @ 0x20000... 393307 (100 %)
Read 393307 bytes at 0x20000 in 5.7 seconds (553.1 kbit/s)...

real	0m6.567s
user	0m2.383s
sys	0m0.930s
```

```
$ strace -c -e trace=select,read esptool.py -b 1500000 -p /dev/ttyUSB0 read_flash 0x20000 393307 0x20000-readback.bin
esptool.py v1.0.2-dev
Connecting...
Running Cesanta flasher stub...
Reading 393307 @ 0x20000... 393307 (100 %)
Read 393307 bytes at 0x20000 in 10.6 seconds (295.9 kbit/s)...
% time     seconds  usecs/call     calls    errors syscall
------ ----------- ----------- --------- --------- ----------------
 83.17    0.004521           0    439289           select
 16.83    0.000915           0    429089           read
------ ----------- ----------- --------- --------- ----------------
100.00    0.005436                868378           total
```

## After

```
$ time esptool.py -b 1500000 -p /dev/ttyUSB0 read_flash 0x20000 393307 0x20000-readback.bin
esptool.py v1.0.2-dev
Connecting...
Running Cesanta flasher stub...
Reading 393307 @ 0x20000... 393307 (100 %)
Read 393307 bytes at 0x20000 in 5.8 seconds (547.1 kbit/s)...

real	0m6.624s
user	0m1.833s
sys	0m0.483s
```

```
$ strace -c -e trace=select,read esptool.py -b 1500000 -p /dev/ttyUSB0 read_flash 0x20000 393307 0x20000-readback.bin
esptool.py v1.0.2-dev
Connecting...
Running Cesanta flasher stub...
Reading 393307 @ 0x20000... 393307 (100 %)
Read 393307 bytes at 0x20000 in 4.3 seconds (726.4 kbit/s)...
% time     seconds  usecs/call     calls    errors syscall
------ ----------- ----------- --------- --------- ----------------
 99.26    0.005918           0     38964           select
  0.74    0.000044           0     28764           read
------ ----------- ----------- --------- --------- ----------------
100.00    0.005962                 67728           total
```

### CODE REVIEW

**Comment by projectgus** [comment]
@rojer , @jmattsson - if either of you have any time I'd be really keen to hear what you think of these changes.

Before merging I'd like to confirm confirm that this does what I think it should do on low-powered systems (there is some additional Python-side overhead from using a generator, that might cancel the benefit out!)

**Comment by rojer** [comment]
i really like the idea. i don't see any problem with using a generator, imho it's used exactly as intended.
perhaps the only minor thing i'd change is the name of the variable - `_slip_reader` instead of just `_reader`. other than that, LGTM.

**Comment by rojer** [comment]
went to test on my RPi and found that there is, unfortunately, a compatibility problem: it looks like `in_waiting` is not available in PySerial that comes with Raspbian (jessie, the latest one):

```'Serial' object has no attribute 'in_waiting'```

**Comment by rojer** [comment]
FWIW "before" looks like this:

```root@shepetovka:~/qq/esptool# time ./esptool.py -b 1500000 -p /dev/ttyN21 read_flash 0x20000 393307 0x20000-readback.bin
esptool.py v1.0.2-dev
Connecting...
Running Cesanta flasher stub...
Reading 393307 @ 0x20000... 393307 (100 %)
Read 393307 bytes at 0x20000 in 15.0 seconds (210.0 kbit/s)...

real	0m16.039s
user	0m8.520s
sys	0m3.510s
```

**Comment by projectgus** [comment]
>  don't see any problem with using a generator, imho it's used exactly as intended.

I agree from a code style point of view, I was just more suspect about the performance implications. Worried I'd "fix" a performance regression by introducing a different kind of performance regression!

> perhaps the only minor thing i'd change is the name of the variable - _slip_reader instead of just
> _reader. other than that, LGTM

Done!

> went to test on my RPi and found that there is, unfortunately, a compatibility problem: it looks like 
> in_waiting is not available in PySerial that comes with Raspbian (jessie, the latest one):
>
> 'Serial' object has no attribute 'in_waiting'

Ah, right. Try it now. The `in_waiting` property is new in pyserial 3, I swapped back to the (now deprecated) `inWaiting()` function call.

Angus

**Comment by rojer** [comment]
quite a bit faster:
```
root@shepetovka:~/qq/esptool# time ./esptool.py -b 1500000 -p /dev/ttyN21 read_flash 0x20000 393307 0x20000-readback.bin
esptool.py v1.0.2-dev
Connecting...
Running Cesanta flasher stub...
Reading 393307 @ 0x20000... 393307 (100 %)
Read 393307 bytes at 0x20000 in 9.3 seconds (339.3 kbit/s)...

real	0m10.312s
user	0m1.970s
sys	0m0.670s
```

**Comment by projectgus** [comment]
Thanks @rojer. I forgot I hadn't merged this yet.

**Pull request merged**
