### PR TITLE
write_flash: Show actual flash write speed.

### PR DESCRIPTION
**Pull request by pfalcon**
There're various reports of various port baud speeds non-working (or
working), show actual write speed should provide more insight into
that.

### CODE REVIEW

**Comment by pfalcon** [comment]
See e.g. https://github.com/themadinventor/esptool/issues/44

**Comment by pfalcon** [comment]
Updated to apply cleanly on the current master.

**Comment by pfalcon** [comment]
This patch is now available in https://github.com/pfalcon/esptool/tree/esp-open-sdk , to be used by https://github.com/pfalcon/esp-open-sdk

**Comment by pfalcon** [comment]
Any response to this patch?

**Comment by projectgus** [comment]
Yes indeed! Merged with a couple of minor tweaks in 765cf23f8.

**Comment by pfalcon** [comment]
Thanks!

**Pull request merged**
