### PR TITLE
workaround for bug in SPIEraseArea

### PR DESCRIPTION
**Pull request by jkent**
This is a cleaner rewrite of the code in bug #33 by iggr.  Also added a fake flash_begin so flash_finish returns sucessfully.  See also #48 and #51.

### CODE REVIEW

**Comment by jkent** [comment]
I'm curious if the behavior for DIO from #52 should actually be used as the default?

**Comment by gelraen** [comment]
FYI, I did some analysis on how and why this fix works: https://cesanta.com/blog/esp8266-flash-erasing-issue.shtml

**Comment by flyashi** [comment]
After debugging for hours, this solved my issue. Please accept this pull request and save future me's the hassle!

**Comment by jkent** [comment]
@themadinventor *poke*

**Pull request merged**
